//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STH_Autopricer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("email")]
        public string sth_email {
            get {
                return ((string)(this["sth_email"]));
            }
            set {
                this["sth_email"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("password")]
        public string sth_password {
            get {
                return ((string)(this["sth_password"]));
            }
            set {
                this["sth_password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool sth_autologin {
            get {
                return ((bool)(this["sth_autologin"]));
            }
            set {
                this["sth_autologin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public decimal SettingMinProfitNUD {
            get {
                return ((decimal)(this["SettingMinProfitNUD"]));
            }
            set {
                this["SettingMinProfitNUD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13")]
        public decimal SettingMaxProfitNUD {
            get {
                return ((decimal)(this["SettingMaxProfitNUD"]));
            }
            set {
                this["SettingMaxProfitNUD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.50")]
        public decimal SettingRegressionValue {
            get {
                return ((decimal)(this["SettingRegressionValue"]));
            }
            set {
                this["SettingRegressionValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal SettingOrderQuantityNUD {
            get {
                return ((decimal)(this["SettingOrderQuantityNUD"]));
            }
            set {
                this["SettingOrderQuantityNUD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public decimal SettingOrderMaxPriceNUD {
            get {
                return ((decimal)(this["SettingOrderMaxPriceNUD"]));
            }
            set {
                this["SettingOrderMaxPriceNUD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal SettingProxyCount {
            get {
                return ((decimal)(this["SettingProxyCount"]));
            }
            set {
                this["SettingProxyCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SettingLinearRegression {
            get {
                return ((bool)(this["SettingLinearRegression"]));
            }
            set {
                this["SettingLinearRegression"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SettingQuantityCheckBox {
            get {
                return ((bool)(this["SettingQuantityCheckBox"]));
            }
            set {
                this["SettingQuantityCheckBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SettingMaxOrderPriceCheckBox {
            get {
                return ((bool)(this["SettingMaxOrderPriceCheckBox"]));
            }
            set {
                this["SettingMaxOrderPriceCheckBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingCheckOnlySellPrice {
            get {
                return ((bool)(this["SettingCheckOnlySellPrice"]));
            }
            set {
                this["SettingCheckOnlySellPrice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingChangeOnlyUp {
            get {
                return ((bool)(this["SettingChangeOnlyUp"]));
            }
            set {
                this["SettingChangeOnlyUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SettingProxyCheck {
            get {
                return ((bool)(this["SettingProxyCheck"]));
            }
            set {
                this["SettingProxyCheck"] = value;
            }
        }
    }
}
